### ISSUE TITLE
Adding this E2 to my public list (E2S)

### ISSUE THREAD

**Issue by Gaerisson** [marluxia95/public-e2s#1]
Hello, first, I wanted to congratulate you for your E2s and to thank you for your trust with my Youtube to MP3 API :)

I had a question, would you agree that I add the Expression 2 "yt_player" to my public E2 list ( http://e2s.gaerisson-softs.fr/list ) ?
(of course this E2 will be listed with your steam profile if you agree and I will link this github project in description)

( This website is not really popular but I could help new users of my api to have an exemple and I will see to update this website, it start to be old :D )

Many thanks for your response and sorry, it is not the best place for this request but that the only way I saw to contact you ^^

**Comment by marluxia95** [comment]
@Gaerisson Sure, you can add my youtube player E2 to your public E2 list. I will probably update this player and add more features that the old one used to have, which I unfortunately lost. Thank you and sorry for answering so late, for some reason it didn't notify me or I just did not realize.

**Comment by Gaerisson** [comment]
> @Gaerisson Sure, you can add my youtube player E2 to your public E2 list. I will probably update this player and add more features that the old one used to have, which I unfortunately lost. Thank you and sorry for answering so late, for some reason it didn't notify me or I just did not realize.

Thank you, no problem about your late answer ! :)
